services:

  app:
    image: spotify-game
    ports: 
      - 80:3000
      - 9000:9000
    depends_on:
      - redis
    volumes:
      - .:/app
    
  crawler:
    image: spotify-game-crawler
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on:
      - redis
    volumes:
    - ./crawler:/app

  redis:
    image: redis
