services:
  redis:
    image: redis
    volumes:
      - redis-dump:/data

  app:
    image: node
    depends_on:
      - redis
    volumes: 
      - ./api:/api
    working_dir: /api
    command: node app.js
    
  crawler:
    image: node
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on: 
      - redis
    volumes: 
      - ./crawler:/crawler
    working_dir: /crawler
    command: ./daemon.js

  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - app
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/public
      - ./proxy/certs:/etc/certs

volumes:
  redis-dump:
